id: CVE-Search-Test
version: -1
contentitemfields:
  propagationLabels:
    - all
name: CVE-Search-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: "62"
    type: start
    task:
      id: "62"
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "1":
    id: "1"
    taskid: "63"
    type: regular
    task:
      id: "63"
      version: -1
      name: cve-latest
      description: Retruns the latest updated CVEs.
      script: CVESearch_V2|||cve-latest
      type: regular
      iscommand: true
      brand: CVESearch_V2
    nexttasks:
      '#none#':
        - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "2":
    id: "2"
    taskid: "72"
    type: regular
    task:
      id: "72"
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "3":
    id: "3"
    taskid: "74"
    type: condition
    task:
      id: "74"
      version: -1
      name: Check if cve-latest return 30 entries
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
        - "4"
      "yes":
        - "6"
    separatecontext: false
    conditions:
      - label: "yes"
        condition:
          - - operator: isEqualNumber
              left:
                value:
                  complex:
                    root: CVE
                    accessor: ID
                    transformers:
                      - operator: count
                iscontext: true
              right:
                value:
                  simple: "30"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "4":
    id: "4"
    taskid: "73"
    type: regular
    task:
      id: "73"
      version: -1
      name: Error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: cve-latest did not return 30 last entires
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 980,
          "y": 870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "6":
    id: "6"
    taskid: "75"
    type: regular
    task:
      id: "75"
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "7"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "7":
    id: "7"
    taskid: "86"
    type: regular
    task:
      id: "86"
      version: -1
      name: search for cve with one cve_id
      description: Search CVE by ID
      script: CVESearch_V2|||cve-search
      type: regular
      iscommand: true
      brand: CVESearch_V2
    nexttasks:
      '#none#':
        - "8"
    scriptarguments:
      cve_id:
        simple: CVE-2015-6541
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "8":
    id: "8"
    taskid: "87"
    type: condition
    task:
      id: "87"
      version: -1
      name: Check cve-search result
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
        - "12"
    separatecontext: false
    conditions:
      - label: "yes"
        condition:
          - - operator: isEqualString
              left:
                value:
                  simple: CVE.ID
                iscontext: true
              right:
                value:
                  simple: CVE-2015-6541
          - - operator: isEqualNumber
              left:
                value:
                  simple: CVE.CVSS
                iscontext: true
              right:
                value:
                  simple: "6.8"
          - - operator: isEqualString
              left:
                value:
                  simple: CVE.Published
                iscontext: true
              right:
                value:
                  simple: 2016-04-08T14:59:00
          - - operator: isEqualString
              left:
                value:
                  simple: CVE.Modified
                iscontext: true
              right:
                value:
                  simple: 2016-04-11T17:44:00
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "9":
    id: "9"
    taskid: "85"
    type: title
    task:
      id: "85"
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "10":
    id: "10"
    taskid: "88"
    type: regular
    task:
      id: "88"
      version: -1
      name: search for cve with multiple cve_ids
      description: Search CVE by ID
      script: CVESearch_V2|||cve-search
      type: regular
      iscommand: true
      brand: CVESearch_V2
    nexttasks:
      '#none#':
        - "11"
    scriptarguments:
      cve_id:
        simple: CVE-2014-1234,CVE-2014-1235,CVE-2014-1236
      cveId: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "11":
    id: "11"
    taskid: "92"
    type: condition
    task:
      id: "92"
      version: -1
      name: Check cve-search result
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
        - "9"
    separatecontext: false
    conditions:
      - label: "yes"
        condition:
          - - operator: isEqualNumber
              left:
                value:
                  complex:
                    root: CVE
                    accessor: ID
                    transformers:
                      - operator: count
                iscontext: true
              right:
                value:
                  simple: "3"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "12":
    id: "12"
    taskid: "90"
    type: regular
    task:
      id: "90"
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "10"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2075,
        "width": 910,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: 0ed26d4a-2d5e-4d28-849b-806d1e9f7833
